# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(474, 500)
        Form.setMinimumSize(QtCore.QSize(0, 500))
        Form.setMaximumSize(QtCore.QSize(16777215, 500))
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(290, 430, 171, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_add = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout.addWidget(self.pushButton_add)
        self.pushButton_dell = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_dell.setObjectName("pushButton_dell")
        self.horizontalLayout.addWidget(self.pushButton_dell)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(20, 10, 171, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_save = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_5.addWidget(self.pushButton_save)
        self.pushButton_load = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout_5.addWidget(self.pushButton_load)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(20, 210, 441, 211))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 70, 447, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(64, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBox_modes = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_modes.setMinimumSize(QtCore.QSize(128, 0))
        self.comboBox_modes.setObjectName("comboBox_modes")
        self.horizontalLayout_2.addWidget(self.comboBox_modes)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(64, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.spinBox_count = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox_count.setObjectName("spinBox_count")
        self.horizontalLayout_3.addWidget(self.spinBox_count)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(64, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.doubleSpinBox_dist = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.doubleSpinBox_dist.setObjectName("doubleSpinBox_dist")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_dist)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_use_field = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_use_field.setObjectName("checkBox_use_field")
        self.horizontalLayout_9.addWidget(self.checkBox_use_field)
        self.checkBox_allow_z = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_allow_z.setObjectName("checkBox_allow_z")
        self.horizontalLayout_9.addWidget(self.checkBox_allow_z)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.doubleSpinBox_radius = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.doubleSpinBox_radius.setObjectName("doubleSpinBox_radius")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_radius)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.doubleSpinBox_force = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.doubleSpinBox_force.setObjectName("doubleSpinBox_force")
        self.horizontalLayout_8.addWidget(self.doubleSpinBox_force)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 160, 155, 28))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.doubleSpinBox_speed = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_speed.setObjectName("doubleSpinBox_speed")
        self.horizontalLayout_10.addWidget(self.doubleSpinBox_speed)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_add.setText(_translate("Form", "Add"))
        self.pushButton_dell.setText(_translate("Form", "Del"))
        self.pushButton_save.setText(_translate("Form", "Save"))
        self.pushButton_load.setText(_translate("Form", "Load"))
        self.label.setText(_translate("Form", "Mode:"))
        self.label_2.setText(_translate("Form", "Count:"))
        self.label_3.setText(_translate("Form", "Distince:"))
        self.checkBox_use_field.setText(_translate("Form", "Use field"))
        self.checkBox_allow_z.setText(_translate("Form", "allow z"))
        self.label_4.setText(_translate("Form", "Radius safe"))
        self.label_5.setText(_translate("Form", "force"))
        self.label_6.setText(_translate("Form", "Speed m/s"))

